language: node_js
node_js:
  - '6'
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache
matrix:
  fast_finish: true
before_install:
  - 'export DISPLAY=:99.0'
  - sh -e /etc/init.d/xvfb start
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version
before_script:
  - git config --global user.email "taras@embersherpa.com"
  - git config --global user.name "Taras Mankovski"
install:
  - npm install
  - bower install
script:
  - 'COVERAGE=true node_modules/.bin/ember try:each --skip-cleanup'
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
