# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: true
      matrix:
        # test the current and previous LTS as well as latest stable release
        ember:
          [
            "ember-lts-3.16",
            "ember-lts-3.20",
            "ember-beta",
            "ember-default-with-jquery",
            "ember-classic",
            "ember-release",
          ]
        experimental: [false]
        include:
          - ember: "ember-canary"
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - name: Node setup
        uses: actions/setup-node@v2.1.2
        with:
          # test addons with the same minimum supported node version as Ember CLI
          node-version: "12.x"
      - name: Tests
        run: |
          npm ci
          npm run lint
          npx ember try:one ${{ matrix.ember }}
